### ISSUE TITLE
Use case discussion

### ISSUE THREAD

**Issue by akatav** [nadavyayon/Intensify3D#3]
Hi
I have two 3d tiff stacks along axial plane showing dendrite segments. The 2 stacks are from imaging sessions conducted on different days before and after fluorescent viral injection. 
The brightness histograms of the 2 tiff stacks vary a bit, not too much though. 
The goal is to detect fluorescence expression in the 2nd day images. How must I use Intensify3d to do this ? I suppose the 2 stacks have to first be normalized. 
Any advice will be very helpful.

**Comment by nadavyayon** [comment]
Hi Thanks for your inquiry
I would recommend to place each stack into a folder. 
Then, select the parent folder containing these 2 folders.
In the next step, select an image where the signal is clearly shown and use the sidebar so that as much of the signal is selected without selecting much background, a few pixels here and there are fine. 
Next you should estimate the size or width of your signal, in your case dendrites to set the spatial filter as follows:
if the width of the dendrite is 20 pixels, go with a spatial filter of at least 40-50. 
Both maximum background intensity and the spatial filter are meant to help the algorithm estimate the background with as little interference from the signal as possible.

As to the normalization, don't use background detection, try semi quantile for within sample and contrast stretch for between sample. 

That's basically it, if you have further question let me know 

Nadav
